// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnfiacldpmvzhgfnekqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZmlhY2xkcG12emhnZm5la3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTkyNzMsImV4cCI6MjA2OTAzNTI3M30.PE3n2b9Z8hM2twT-Ri9EpKlTCkMxiRMYuyKVopb-jGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});